<?php
session_start();
ob_start();
require 'mail/class.phpmailer.php';
include_once('mail/mailPass.php');
include_once('config.php');
$mail = new PHPMailer();
$mail->IsSMTP();
$mail->Mailer = 'smtp';
$mail->SMTPAuth = true;
$mail->Host = 'smtp.gmail.com'; 
$mail->Port = 587;
$mail->SMTPSecure = 'tls';


$mail->Username = "ankitk3000@gmail.com";
$mail->Password = $pass;
 
$mail->IsHTML(true); 
$mail->SingleTo = true;
 
$mail->From = "ankitk3000@gmail.com";
$mail->FromName = "Research Bros";

$email = $_SESSION['emailID'];
$name = $_SESSION['name'];

//generate random password
$len = 16;
$word = array_merge(range('a', 'z'), range('A', 'Z'),range('0','9'));
shuffle($word);
$random = substr(implode($word), 0, $len);

$mail->addAddress($email,$name); 
$mail->Subject = "Research Bros Signup";
$mail->Body = "Auto generated email. <br/>Your autogenerated password is : " . $random . "<br/>Please change it as soon as possible";

$connect = mysqli_connect($servername,$username,$password,$dbname);

$query = "UPDATE user SET password='$random' WHERE emailID='$email';";

$result = mysqli_query($connect,$query);

$mail->Send();
header('Location:ListlabSubmit.php');

    ?>
	